### PR TITLE
Core: Migrate to Nextra

### PR DESCRIPTION
**Pull request by Gary50613**
This PR is originally made by @SonMooSans #87 

## Todo

1. [x] pick a chinese font
2. [x] renew partner list
3. [x] missing home page footer
4. [x] add API route for resolving users count
6. [x] check if some SEO issues exist and deal with it
7. [x] integrate with [Yeecord App](https://app.yeecord.com) with button or user avatar at the header

## 起飛前確認事項

- [x] 我已詳細確認編輯之文件有符合 [CONTRIBUTING.md](https://github.com/yeecord/docs/blob/master/CONTRIBUTING.md) 文件規範

### CODE REVIEW

**Review by wolf-yuan-6115 — CHANGES_REQUESTED** [review]
Commented on Vercel deployment

**Comment by Nat1anWasTaken** [comment]
I'll add the new document content after this PR is merged.

**Review by wolf-yuan-6115 — APPROVED** [review]

**Comment by Gary50613** [comment]
# Before merging

- [ ] Check lighthouse suggestions
- [ ] add TOC for blog
- [ ] SSG tags page

**Comment by Gary50613** [comment]
anything to fix? or we will start merging

**Pull request merged**
